source "https://rubygems.org"

gem "jekyll", ">= 3.9.0"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
